#!/bin/bash
# Test script to demonstrate slash command usage

echo "🧪 Testing Claude Slash Commands for GitHub Actions"
echo ""
echo "Available commands installed:"
echo "  /actions          - Full GitHub Actions improvement"
echo "  /actions-create   - Create new workflows"
echo "  /actions-fix      - Fix failing workflows"
echo "  /actions-improve  - Improve existing workflows"
echo "  /actions-security - Add security scanning"
echo "  /ci               - Quick CI workflow creation"
echo ""
echo "To test interactively:"
echo "1. Navigate to any Git repository"
echo "2. Run: claude"
echo "3. Type any of the slash commands above"
echo ""
echo "Example usage:"
echo "  cd ~/my-python-project"
echo "  claude"
echo "  > /actions"
echo "  (Claude will analyze and improve all GitHub Actions)"
echo ""
echo "  > /ci"
echo "  (Claude will create a quick CI pipeline)"
echo ""
echo "  > /actions-security"
echo "  (Claude will add security scanning workflows)"
echo ""
echo "The slash commands will automatically:"
echo "✅ Detect your project type (Python, Node.js, Rust, Go, etc.)"
echo "✅ Create appropriate workflows if none exist"
echo "✅ Improve existing workflows with best practices"
echo "✅ Process multiple workflows concurrently"
echo "✅ Apply security hardening and modern practices"
echo ""
echo "🎉 Ready to test! Try '/actions' in any Git repository."