name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Run build script
      if: hashFiles('scripts/build.sh') != '' || hashFiles('build.sh') != ''
      run: |
        if [ -f "scripts/build.sh" ]; then
          chmod +x scripts/build.sh && ./scripts/build.sh
        elif [ -f "build.sh" ]; then
          chmod +x build.sh && ./build.sh
        fi
    
    - name: Run test script
      if: hashFiles('scripts/test.sh') != '' || hashFiles('test.sh') != ''
      run: |
        if [ -f "scripts/test.sh" ]; then
          chmod +x scripts/test.sh && ./scripts/test.sh
        elif [ -f "test.sh" ]; then
          chmod +x test.sh && ./test.sh
        fi
    
    - name: Run make targets
      if: hashFiles('Makefile') != ''
      run: |
        if make -n test 2>/dev/null; then
          make test
        elif make -n build 2>/dev/null; then
          make build
        fi